### PR TITLE
Bower - package manager to js plugins

### PR DESCRIPTION
**Pull request by mfdeveloper**
Moved javascript plugins from folder **plugins** to **bower_components** to allow use `bower install` command to download this theme. After accept this merge request, you can perform: 

``` shell
bower install devoops-bootstrap-theme
```

Or add in your `bower.json`

``` javascript
"dependencies": {
    "devoops-bootstrap-theme":">=2.0"
}
```

**Obs:** Temporarilly, was added the `git://github.com/mfdeveloper/devoops.git` url repo. I will change this addres in _bower register_, after that this pull request will be finish!

### CODE REVIEW

**Comment by nnmware** [comment]
Felipe, thank for your work. 
But
1) We not use/know bower and node, and can't test this pull request
2) If we right understand - changed paths for many plugins, but in devoops.js no changes.
With this pull request- theme not usable.
Sorry.

**Comment by mfdeveloper** [comment]
Hello @nnmware. Thank you so much for your fast response :smile: 

I understand your point. The paths in ```devoops.js``` file were updated just now! But, I don't understand because @devoopsme close this issue. If you not use ``` bower ```, why do you not want use now? The dependencies management is hard today, and with bower this is so much fast and easy to use together another front-end tools (gulp, grunt...) in a application that use this theme. In few minutes, you can test my pull request easily. Just look at the getting started in official site http://bower.io/

Do you have some doubt about? Can I help you to test this pull request?

**Comment by jomo666** [comment]
Hello. Not everybody could use bower. (For example not every company allows install it). Myself can't use it too. Thank you for the great work anyway - unfortunately, with bower - it is unusable for me too.

**Comment by mfdeveloper** [comment]
Hello @jomo666. I understand now. My suggestion is keep a branch or tag version with **bower support**. The tag version is verified automatically by bower if a _bower.json_ file exists in repo. 

What do you think about this approach?

**Comment by jomo666** [comment]
Thats would be great. Or just create the master with bower and together, if you could maintain a branch which doesn't depends on bower. Any approach which results "bower independency" is simply great. :) Thank you for your quick answer.

**Comment by mfdeveloper** [comment]
Great @jomo666. What I need to do now? The @devoopsme needs reopen this pull request, and merge this changes with a tag or add my branch **bower_dependencies** into this repo, no? I did others changes and commit's, but I do'nt push to here yet. I'm waiting for a decision now :smile:

**Comment by jomo666** [comment]
Huh... honestly, i'm an gitnoob and haven't idea about the process. I just commented (and concerned about) the "bower independence" - but, sorry - I haven't idea about all around. In the worst case, just ignore my comments. :) :)

**Comment by devoopsme** [comment]
Sorry. we don't have time for make another branches, etc.
But
It's open source, you can free fork code and make all you want.

**Comment by mfdeveloper** [comment]
Pretty awesome @devoopsme ! I created two tags for theme versions in my forked repo: https://github.com/mfdeveloper/devoops and I registered this in [bower.io](http://bower.io) packages list with the name `devoops-bootstrap-theme`

So, if someone wish use `bower` + `gulp` with this theme, now it's possible :)

**Pull request closed without merging**
